apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mediawiki
  name: mediawiki
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mediawiki
    spec:
      containers:
      - image: mediawiki
        name: mediawiki
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/images
          name: mediawiki-images
        - mountPath: /var/www/data
          name: mediawiki-data
        - name: config-volume
          mountPath: /var/www/html/LocalSettings.php
          subPath: LocalSettings.php
      restartPolicy: Always
      volumes:
      - name: mediawiki-images
        persistentVolumeClaim:
          claimName: mediawiki-images
      - name: mediawiki-data
        persistentVolumeClaim:
          claimName: mediawiki-data
      - name: config-volume
        configMap:
          name: mediawiki-config
