apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mediawiki
  name: mediawiki
spec:
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: NodePort 
  selector:
    io.kompose.service: mediawiki
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediawiki
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: wiki.soynet.local
    http:
      paths:
      - path: /
        backend:
          serviceName: mediawiki
          servicePort: 80

