apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: network-services
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-udp
  namespace: default
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.43
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: client-udp
    port: 67
    protocol: UDP
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
