---
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress-service
  namespace: default
spec:
  selector:
    app: nginx
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: LoadBalancer
  loadBalancerIP: 192.168.1.42
